export const addEmployeeFormData = [
  {
    label: "Site Name",
    type: "dropdown",
    placeholder: ["Site1", "Site2", "Site3"],
    required: true,
    id: "Site Name1",
  },
  {
    label: "Depot",
    type: "dropdown",
    placeholder: ["Depot1", "Depot2", "Depot3"],
    required: true,
    id: "Depot2",
  },
  {
    label: "Aadhar Number",
    type: "number",
    placeholder: "Enter Aadhar Number",
    required: true,
    id: "Aadhar Number3",
  },
  {
    label: "Full Name",
    type: "text",
    placeholder: "Enter Name",
    required: true,
    id: "Full Name4",
  },
  {
    label: "Date of Birth",
    type: "date",
    placeholder: "Enter Date of birth",
    required: true,
    id: "Date of Birth5",
  },
  {
    label: "Father's Name",
    type: "text",
    placeholder: "Enter Father's name",
    required: true,
    id: "Father's Name6",
  },
  {
    label: "Address",
    type: "text",
    placeholder: "Enter Current Address",
    required: true,
    id: "Address7",
  },
  {
    label: "Mobile Number",
    type: "number",
    placeholder: "Enter mobile number",
    required: true,
    id: "Mobile Number8",
  },
  {
    label: "Offered Salary",
    type: "number",
    placeholder: "Enter offered salary",
    required: true,
    id: "Offered Salary9",
  },
  {
    label: "HRA",
    type: "number",
    placeholder: "Enter HRA Salary",
    required: true,
    id: "HRA10",
  },
  {
    label: "Designation",
    type: "dropdown",
    placeholder: ["Senior", "Mid", "Junior"],
    required: true,
    id: "Designation11",
  },
  {
    label: "Date of Joining",
    type: "date",
    placeholder: "Enter Date of Joining",
    required: true,
    id: "Date of Joining12",
  },
  {
    label: "Upload Aadhar Card",
    type: "file",
    placeholder: "",
    required: true,
    id: "Upload Aadhar Card13",
  },
  {
    label: "Upload Photo",
    type: "file",
    placeholder: "",
    required: true,
    id: "Upload Photo14",
  },
  {
    label: "Form 11",
    type: "file",
    placeholder: "",
    required: true,
    id: "Form 1115",
  },
  {
    label: "Form 2",
    type: "file",
    placeholder: "",
    required: true,
    id: "Form 216",
  },
  {
    label: "Form1 Under E5",
    type: "file",
    placeholder: "",
    required: true,
    id: "Form1 Under E517",
  },
  {
    label: "Form of nomination for unpaid wages",
    type: "file",
    placeholder: "",
    required: true,
    id: "Form of nomination for unpaid wages18",
  },
  {
    label: "Bank A/C Number",
    type: "number",
    placeholder: "Enter Bank A/C Number",
    required: true,
    id: "Bank A/C Number19",
  },
  {
    label: "Bank Name",
    type: "text",
    placeholder: "Enter Bank Name",
    required: true,
    id: "Bank Name20",
  },
  {
    label: "Enter IFSC Code",
    type: "text",
    placeholder: "Enter Enter IFSC Code",
    required: true,
    id: "Enter IFSC Code21",
  },
  {
    label: "Upload Soft Copy of Passbook",
    type: "file",
    placeholder: "",
    required: true,
    id: "Upload Soft Copy of Passbook22",
  },
  {
    label: "Railway ID",
    type: "text",
    placeholder: "Enter Railway ID",
    required: true,
    id: "Railway ID23",
  },
  {
    label: "Category",
    type: "dropdown",
    placeholder: ["Senior", "Mid", "Junior"],
    required: true,
    id: "Category24",
  },
  {
    label: "Gender",
    type: "dropdown",
    placeholder: ["Male", "Female", "Other"],
    required: true,
    id: "Gender25",
  },
  {
    label: "Qualification",
    type: "dropdown",
    placeholder: ["Bachelor's", "Master's", "Doctorate"],
    required: true,
    id: "Qualification26",
  },
];
