export const addEmployeeFormData = [
  {
    label: "Site Name",
    name: "siteName",
    type: "dropdown",
    placeholder: ["Site1", "Site2", "Site3"],
    required: true,
    id: "Site_Name1",
  },
  {
    label: "Depot",
    name: "depot",
    type: "dropdown",
    placeholder: ["Depot1", "Depot2", "Depot3"],
    required: true,
    id: "Depot2",
  },
  {
    label: "Aadhar Number",
    name: "aadharNumber",
    type: "number",
    placeholder: "Enter Aadhar Number",
    required: true,
    id: "Aadhar_Number3",
  },
  {
    label: "Full Name",
    name: "fullName",
    type: "text",
    placeholder: "Enter Name",
    required: true,
    id: "Full_Name4",
  },
  {
    label: "Date of Birth",
    name: "DOB",
    type: "date",
    placeholder: "Enter Date of birth",
    required: true,
    id: "Date_of_Birth5",
  },
  {
    label: "Father's Name",
    name: "FatherName",
    type: "text",
    placeholder: "Enter Father's name",
    required: true,
    id: "Father's_Name6",
  },
  {
    label: "Address",
    name: "address",
    type: "text",
    placeholder: "Enter Current Address",
    required: true,
    id: "Address7",
  },
  {
    label: "Mobile Number",
    name: "mobileNumber",
    type: "number",
    placeholder: "Enter mobile number",
    required: true,
    id: "Mobile_Number8",
  },
  {
    label: "Offered Salary",
    name: "offeredSalary",
    type: "number",
    placeholder: "Enter offered salary",
    required: true,
    id: "Offered_Salary9",
  },
  {
    label: "HRA",
    name: "HRA",
    type: "number",
    placeholder: "Enter HRA Salary",
    required: true,
    id: "HRA10",
  },
  {
    label: "Designation",
    name: "designation",
    type: "dropdown",
    placeholder: ["Senior", "Mid", "Junior"],
    required: true,
    id: "Designation11",
  },
  {
    label: "Date of Joining",
    name: "dateOfJoining",
    type: "date",
    placeholder: "Enter Date of Joining",
    required: true,
    id: "Date_of_Joining12",
  },
  {
    label: "Upload Aadhar Card",
    name: "uploadAadharCard",
    type: "file",
    placeholder: "",
    required: true,
    id: "Upload_Aadhar_Card13",
  },
  {
    label: "Upload Photo",
    name: "uploadPhoto",
    type: "file",
    placeholder: "",
    required: true,
    id: "Upload_Photo14",
  },
  {
    label: "Form 11",
    name: "form11",
    type: "file",
    placeholder: "",
    required: true,
    id: "Form_1115",
  },
  {
    label: "Form 2",
    name: "form2",
    type: "file",
    placeholder: "",
    required: true,
    id: "Form_216",
  },
  {
    label: "Form1 Under E5",
    name: "form1UnderE5",
    type: "file",
    placeholder: "",
    required: true,
    id: "Form1_Under_E517",
  },
  {
    label: "Form of nomination for unpaid wages",
    name: "FormOfNominationForUnpaidWages",
    type: "file",
    placeholder: "",
    required: true,
    id: "Form_of_nomination for_unpaid_wages18",
  },
  {
    label: "Bank A/C Number",
    name: "bankAccNumber",
    type: "number",
    placeholder: "Enter Bank A/C Number",
    required: true,
    id: "Bank_A/C_Number19",
  },
  {
    label: "Bank Name",
    name: "bankName",
    type: "text",
    placeholder: "Enter Bank Name",
    required: true,
    id: "Bank_Name20",
  },
  {
    label: "Enter IFSC Code",
    name: "enterIfscCode",
    type: "text",
    placeholder: "Enter Enter IFSC Code",
    required: true,
    id: "Enter_IFSC_Code21",
  },
  {
    label: "Upload Soft Copy of Passbook",
    name: "softCopyOfPassbook",
    type: "file",
    placeholder: "",
    required: true,
    id: "Upload_Soft_Copy_of_Passbook22",
  },
  {
    label: "Railway ID",
    name: "railwayID",
    type: "text",
    placeholder: "Enter Railway ID",
    required: true,
    id: "Railway_ID23",
  },
  {
    label: "Category",
    name: "category",
    type: "dropdown",
    placeholder: ["Senior", "Mid", "Junior"],
    required: true,
    id: "Category24",
  },
  {
    label: "Gender",
    name: "gender",
    type: "dropdown",
    placeholder: ["Male", "Female", "Other"],
    required: true,
    id: "Gender25",
  },
  {
    label: "Qualification",
    name: "qualification",
    type: "dropdown",
    placeholder: ["Bachelor's", "Master's", "Doctorate"],
    required: true,
    id: "Qualification26",
  },
];
